# use the tidyverse rocker image, as it contains devtools preinstalled
image: rocker/tidyverse
# image: rocker/r-base

stages:
  - build
  - test
  - deploy

before_script:
  - R -e 'devtools::install_deps(dep = T)'

buildbinary:
  stage: build
  script:
    - R -e 'devtools::check(vignettes = FALSE, error_on = "error")'

unittests:
  stage: test
  script:
    - r -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'