## |------------------------------------------------------------------------| #
# SourceSilent ----
## |------------------------------------------------------------------------| #

#' Silently source R script with optional message and warning suppression
#'
#' This function sources an R script file with options to suppress messages
#' and/or warnings. It is useful for running scripts that generate a lot of
#' console output that is not needed.
#' @name SourceSilent
#' @param File A string specifying the path of the file to be sourced.
#' @param Messages Logical; if `TRUE` (default), messages generated by the
#'   script are shown. If `FALSE`, messages are suppressed.
#' @param Warnings Logical; if `TRUE` (default), warnings generated by the
#'   script are shown. If `FALSE`, warnings are suppressed.
#' @param ... Additional arguments passed to the [source] function.
#' @author Ahmed El-Gabbas
#' @return It is used for its side effect of sourcing a file with optional
#'   suppression of messages and warnings.
#' @export

SourceSilent <- function(File, Messages = TRUE, Warnings = TRUE, ...) {

  if (is.null(File)) {
    stop("File cannot be NULL", call. = FALSE)
  }

  if (Messages && Warnings) {
    File %>%
      source(...) %>%
      utils::capture.output(file = nullfile())
  }

  if (isFALSE(Messages) && isFALSE(Warnings)) {
    File %>%
      source(...) %>%
      utils::capture.output(file = nullfile()) %>%
      suppressMessages() %>%
      suppressWarnings()
  }

  if (Messages && isFALSE(Warnings)) {
    File %>%
      source(...) %>%
      utils::capture.output(file = nullfile()) %>%
      suppressWarnings()
  }

  if (isFALSE(Messages) && Warnings) {
    File %>%
      source(...) %>%
      utils::capture.output(file = nullfile()) %>%
      suppressMessages()
  }

  return(invisible(NULL))

}
