# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Invert a matrix
#'
#' Computes the inverse of a square matrix using Armadillo's `inv` function.
#'
#' @param x A square matrix to be inverted.
#' @return The inverted matrix of the same dimensions as `x`.
#' //' @export
Solve1 <- function(x) {
    .Call(`_IASDT_R_Solve1`, x)
}

#' Solve a system of linear equations
#'
#' Solves a system of linear equations `A * X = B` for `X`, where `A` is a
#' square matrix and `B` is a matrix of compatible dimensions.
#'
#' @param A A square matrix representing the coefficients.
#' @param B A matrix or vector representing the constants.
#' @return The solution matrix or vector `X`.
#' @export
Solve2 <- function(A, B) {
    .Call(`_IASDT_R_Solve2`, A, B)
}

#' Solve a system of linear equations for a vector
#'
#' Solves a system of linear equations `A * x = B` where `A` is a square
#' matrix and `B` is a vector.
#'
#' @param A A square matrix of coefficients.
#' @param B A vector of constants.
#' @return The solution vector `x`.
#' @export
Solve2vect <- function(A, B) {
    .Call(`_IASDT_R_Solve2vect`, A, B)
}

#' Fast Normal CDF
#'
#' Computes the cumulative distribution function of the normal distribution
#' for a numeric vector using a fast approximation.
#'
#' @param x A numeric vector for which the CDF should be computed.
#' @return A numeric vector of CDF values for each element in `x`.
#' @export
fast_pnorm <- function(x) {
    .Call(`_IASDT_R_fast_pnorm`, x)
}

#' Exponential of Negative Division
#'
#' Computes the element-wise exponential of the negative division of each
#' element in a matrix by a scalar value.
#'
#' @param D11 A matrix of values to be divided and exponentiated.
#' @param x A scalar divisor.
#' @return A matrix of the same dimensions as `D11`, containing the computed
#' values.
#'
#' @export
exp_neg_div <- function(D11, x) {
    .Call(`_IASDT_R_exp_neg_div`, D11, x)
}

