# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title helper C++ functions for fast matrix computations
#' 
#' @description
#' A collection of efficient C++ functions using RcppArmadillo for common matrix operations, including solving linear systems, computing matrix inverses, approximating normal CDFs, and fast elementwise transformations.
#' 
#' @name cpp_functions
#' @rdname cpp_functions
#' @param A A numeric matrix (for solving, exponential operations, etc.).
#' @param B A numeric matrix or vector (right-hand side for solving linear systems).
#' @param x A numeric matrix, numeric vector, or numeric scalar (depending on the function).
#' 
#' @return 
#' - `solve1()`: A numeric matrix, the inverse of `x`.
#' - `solve2()`: A numeric matrix, the solution to `A * X = B`.
#' - `solve2vect()`: A numeric vector, the solution to `A * x = B`.
#' - `fast_pnorm()`: A numeric vector, CDF values approximated for standard normal distribution.
#' - `exp_neg_div()`: A numeric matrix, elementwise exponential of `-A/x`.
#' 
#' @author Ahmed El-Gabbas
#' @examples
#' 
#' # -----------------------------------------
#' # Example for solve1
#' # -----------------------------------------
#' 
#' N <- 100
#' set.seed(1000)
#' Matrix <- matrix(rnorm(N * N), N, N)
#' all.equal(solve(Matrix), IASDT.R::solve1(Matrix))
#' 
#' # -----------------------------------------
#' # Example for solve2
#' # -----------------------------------------
#' 
#' N <- 100
#' set.seed(1000)
#' A <- matrix(rnorm(N * N), N, N)
#' set.seed(2000)
#' B <- matrix(rnorm(N * N), N, N)
#' all.equal(solve(A, B), IASDT.R::solve2(A, B))
#' 
#' set.seed(2000)
#' B <- matrix(rnorm(N), N, 1)
#' all.equal(solve(A, B), IASDT.R::solve2(A, B))
#' 
#' # -----------------------------------------
#' # Example for solve2vect
#' # -----------------------------------------
#' 
#' N <- 100
#' set.seed(1000)
#' A <- matrix(rnorm(N * N), N, N)
#' set.seed(2000)
#' B <- rnorm(N)
#' all.equal(solve(A, B), as.vector(IASDT.R::solve2vect(A, B)))
#' 
#' # -----------------------------------------
#' # Example for fast_pnorm
#' # -----------------------------------------
#' 
#' set.seed(1000)
#' A <- rnorm(100)
#' all.equal(pnorm(A), IASDT.R::fast_pnorm(A))
#' 
#' # -----------------------------------------
#' # Example for exp_neg_div
#' # -----------------------------------------
#' 
#' N <- 1000
#' set.seed(1000)
#' A <- matrix(rnorm(N * N), N, N)
#' set.seed(2000)
#' x <- rnorm(1)
#' all.equal(exp(-A / x), IASDT.R::exp_neg_div(A, x))
NULL

#' @rdname cpp_functions
#' @export
solve1 <- function(x) {
    .Call(`_IASDT_R_solve1`, x)
}

#' @rdname cpp_functions
#' @export
solve2 <- function(A, B) {
    .Call(`_IASDT_R_solve2`, A, B)
}

#' @rdname cpp_functions
#' @export
solve2vect <- function(A, B) {
    .Call(`_IASDT_R_solve2vect`, A, B)
}

#' @rdname cpp_functions
#' @export
fast_pnorm <- function(x) {
    .Call(`_IASDT_R_fast_pnorm`, x)
}

#' @rdname cpp_functions
#' @export
exp_neg_div <- function(A, x) {
    .Call(`_IASDT_R_exp_neg_div`, A, x)
}

